name: mbed-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs: 
  build-cli-v1:
    container:
      image: ghcr.io/armmbed/mbed-os-env:mbed-os-5.15-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F446RE]
        profile: [release, debug, develop]
        

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          
      -
        name: build-example
        run: |
          set -e
          mbed deploy
          mbed compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
          
  build-cli-v2:
    container:
      image: ghcr.io/armmbed/mbed-os-env:mbed-os-5.15-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F446RE]
        profile: [release, debug, develop]
        

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          
      -
        name: build-example-application
        run: |
          set -e
          mbed-tools deploy
          mbed-tools compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
