name: mbed-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

      
jobs:
  publish:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:mbed-os-5.15-latest
    steps:
      - run: mbed-tools -h
