name: mbed-build-release

on:
  push:
    tags: '*'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs: 
  build:
    container:
      image: ghcr.io/armmbed/mbed-os-env:mbed-os-5.15-latest
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [NUCLEO_F446RE]
        profile: [develop]
        
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          
      -
        name: build
        run: |
          set -e
          mbed deploy
          mbed compile -t GCC_ARM -m ${{ matrix.target }} --profile mbed-profiles/${{ matrix.profile }}.json
      -
        name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: BUILD/${{ matrix.target }}/GCC_ARM-DEVELOP/Project-Template-for-mbed.bin
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.target }}
            LICENSE
            NOTICE.md
